### ISSUE TITLE
Homebridge not showing 2.0.2 available but it is on NPM registry

### ISSUE THREAD

**Issue by adude007** [reartvapps/homebridge-onstar-dev#5]
Was some link broken between the NPM and those of us on 2.0.01? I can’t get homebridge to update the plugin to 2.0.2.

**Comment by Z1mDMan** [comment]
I had to remove and re-add it. After that it’s been good. Make sure to back up your configuration JSON and restore it after (copy/paste it somewhere and then back again)

**Comment by adude007** [comment]
> I had to remove and re-add it. After that it’s been good. Make sure to back up your configuration JSON and restore it after (copy/paste it somewhere and then back again)

Does that break the accessories and automations I have setup?

**Comment by Z1mDMan** [comment]
Not if you put everything back exactly as it was in homebridge. I literally copied the JSON to a notepad, removed the plugin, readded the plugin 2.0.2 and then pasted the JSON back in.

**Comment by adude007** [comment]
> Not if you put everything back exactly as it was in homebridge. I literally copied the JSON to a notepad, removed the plugin, readded the plugin 2.0.2 and then pasted the JSON back in.

Thanks! 

1. Copy Plugin JSON config to a notepad
2. Uninstall plugin, skip restart
3. Install plugin v 2.0.2, skip restart
4. Paste JSON back in to plugin config.
5. Restart child bridge
6. Everything works without issue.
